### ISSUE TITLE
MissingControllerException DocsController

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#202]
# What Occurs
On PROD the following Error is often raised

```
2015-08-28 14:20:58] sitebuilder.DEBUG: exception 'MissingControllerException' with message 'Missing Controller' in /home/meumobi/PROJECTS/meumobi.com/releases/20150731203607/sitebuilder/lib/core/controller/Controller.php:65 Stack trace: #0 /home/meumobi/PROJECTS/meumobi.com/releases/20150731203607/sitebuilder/config/initializers/dispatcher.php(336): Controller::load('DocsController', true) #1 /home/meumobi/PROJECTS/meumobi.com/releases/20150731203607/sitebuilder/lib/lithium/util/collection/Filters.php(183): {closure}('lithium\action\...', Array, Object(lithium\util\collection\Filters)) #2 /home/meumobi/PROJECTS/meumobi.com/releases/20150731203607/sitebuilder/lib/lithium/core/StaticObject.php(126): lithium\util\collection\Filters::run('lithium\action\...', Array, Array) #3 /home/meumobi/PROJECTS/meumobi.com/releases/20150731203607/sitebuilder/lib/lithium/action/Dispatcher.php(124): lithium\core\StaticObject::_filter('run', Array, Object(Closure)) #4 /home/meumobi/PROJECTS/meumobi.com/releases/20150731203607/sitebuilder/config/bootstrap.php(38): lithium\action\Dispatcher::run(Object(lithium\action\Request)) #5 /home/meumobi/PROJECTS/meumobi.com/releases/20150731203607/segments/enterprise/public/index.php(5): {closure}('enterprise') #6 {main} {"component":"general"} 
```

**Comment by t4deu** [comment]
The exception is caused by the  request ```GET http://enterprise.meumobilesite.com/docs/feed.xml```:
```
[ELEFANTE]ks387594:~$ grep '/docs/' /var/log/apache2/partners.meumobi/access.2015-08-28
189.17.194.254 - - [28/Aug/2015:21:26:58 +0200] "GET /docs/feed.xml HTTP/1.1" 200 673 "http://enterprise.meumobilesite.com/docs/feed.xml" "SimplePie/1.3.1 (Feed Parser; http://simplepie.org; Allow like Gecko) Build/20121030175911" 0 / 123810
189.17.194.254 - - [28/Aug/2015:21:27:58 +0200] "GET /docs/feed.xml HTTP/1.1" 200 673 "http://enterprise.meumobilesite.com/docs/feed.xml" "SimplePie/1.3.1 (Feed Parser; http://simplepie.org; Allow like Gecko) Build/20121030175911" 0 / 122603
....
```

The request is made by the extension:
```
> db.extensions.find({url: "http://enterprise.meumobilesite.com/docs/feed.xml"});
{ "_id" : ObjectId("55a8ea3f9a645d77438b4567"), "category_id" : NumberLong(7129), "created" : ISODate("2015-07-17T11:42:55.600Z"), "enabled" : NumberLong(1), "extension" : "rss", "modified" : ISODate("2015-07-31T18:45:11.250Z"), "site_id" : NumberLong(469), "url" : "http://enterprise.meumobilesite.com/docs/feed.xml", "use_html_purifier" : NumberLong(0) }

```

**Comment by t4deu** [comment]
The site domain is **deloitte.meumobi.com**

**Comment by t4deu** [comment]
These extensions have been disabled:
```
[PROD]
{ "_id" : ObjectId("55a8ea3f9a645d77438b4567"), "category_id" : NumberLong(7129), "created" : ISODate("2015-07-17T11:42:55.600Z"), "enabled" : 0, "extension" : "rss", "modified" : ISODate("2015-07-31T18:45:11.250Z"), "site_id" : NumberLong(469), "url" : "http://enterprise.meumobilesite.com/docs/feed.xml", "use_html_purifier" : NumberLong(0) }

[RIMOBI]
{ "_id" : ObjectId("55b133b7701796403e8b4567"), "category_id" : 472, "created" : ISODate("2015-07-23T18:34:31.603Z"), "enabled" : 0, "extension" : "rss", "modified" : ISODate("2015-08-14T14:45:32.148Z"), "priority" : 2, "site_id" : 59, "url" : "http://enterprise.meumobilesite.com/docs/feed.xml", "use_html_purifier" : 1 }
```
