### ISSUE TITLE
Unable to get items from private site on INT, always returns an "authentication required" error

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#46]
I've retrieved Auth token from mongodb, see below
```sh
> db.visitors.find({email:'victor.dias@ipanemax.com'})
{ "_id" : ObjectId("549a0a95b5a5081e3f8b4567"), "email" : "victor.dias@ipanemax.com", "first_name" : "Victor", "last_name" : "Dias", "site_id" : NumberLong(6), "hashed_password" : "c04be0bc82f0abc4c89f2248b46ac305b42902c1", "auth_token" : "b43954d10f7e80e39fc6978e02ecf1155a668df1", "last_login" : "2015-04-06 21:33:02", "should_renew_password" : true, "devices" : [ 	{ 	"uuid" : "b1c69c42-0d9d-71c5-3552-550589379488", 	"push_id" : "APA91bFNoqlghGZj2NX50PmrSHa-1_LvLJtrh2-8na45Alp8nW8XEhVt1n1pgTRsYg_tdJDefUAk34HCuO2FdyoQqnRybz1qdamH7JZNa8fIFtyFD1cgDE7oL0wo-4BgS5TjCgef5olkjZ1236VfCN-638_xM9QfBQ", 	"model" : "GT-I8190L", 	"app_version" : "1.0.0" }, 	{ 	"uuid" : "993C82BA-F94C-4B74-AEB6-702209A0F32B", 	"push_id" : "f522204377bae9f7f5a5e6c65e6c7559c32752e3792c5b3e9634ee15fe577b90", 	"model" : "iPod5,1", 	"app_version" : "1.0.0" }, 	{ 	"uuid" : "1234567890", 	"push_id" : "", 	"model" : "Galaxy S5", 	"app_version" : "1.0.0" } ], "groups" : [ "vip" ] }
>
```
If I call /categories/31/items it raises 401 Unauthorized response, see trace below:

```sh
$ curl -v http://int-meumobi.com/api/infobox.int-meumobi.com/categories/31/items -H "X-Visitor-Token: b43954d10f7e80e39fc6978e02ecf1155a668df1"
* About to connect() to int-meumobi.com port 80 (#0)
*   Trying 37.187.106.27...
* Adding handle: conn: 0x7fa50900a600
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fa50900a600) send_pipe: 1, recv_pipe: 0
* Connected to int-meumobi.com (37.187.106.27) port 80 (#0)
> GET /api/infobox.int-meumobi.com/categories/31/items HTTP/1.1
> User-Agent: curl/7.30.0
> Host: int-meumobi.com
> Accept: */*
> X-Visitor-Token: b43954d10f7e80e39fc6978e02ecf1155a668df1
> 
< HTTP/1.1 401 Unauthorized
< Date: Mon, 06 Apr 2015 19:43:53 GMT
* Server Apache/2.2.22 (Debian) is not blacklisted
< Server: Apache/2.2.22 (Debian)
< Vary: X-Visitor-Token,Accept-Encoding
< Content-Length: 35
< Content-Type: text/html
< 
* Connection #0 to host int-meumobi.com left intact
{"error":"authentication required"}
$
```
If I call /items/latest it raises a 'Missing Controller' error, see trace below:
```sh
curl -v http://int-meumobi.com/api/infobox.int-meumobi.com/latest/items -H "X-Visitor-Token: b43954d10f7e80e39fc6978e02ecf1155a668df1"
* Adding handle: conn: 0x7fa112001a00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fa112001a00) send_pipe: 1, recv_pipe: 0
* About to connect() to int-meumobi.com port 80 (#0)
*   Trying 37.187.106.27...
* Connected to int-meumobi.com (37.187.106.27) port 80 (#0)
> GET /api/infobox.int-meumobi.com/latest/items HTTP/1.1
> User-Agent: curl/7.30.0
> Host: int-meumobi.com
> Accept: */*
> X-Visitor-Token: b43954d10f7e80e39fc6978e02ecf1155a668df1
> 
< HTTP/1.1 200 OK
< Date: Mon, 06 Apr 2015 19:44:42 GMT
* Server Apache/2.2.22 (Debian) is not blacklisted
< Server: Apache/2.2.22 (Debian)
< Vary: X-Visitor-Token,Accept-Encoding
< Content-Length: 1252
< Content-Type: text/html
< 
<pre>exception 'MissingControllerException' with message 'Missing Controller' in /home/meumobi/PROJECTS/int-meumobi.com/releases/20150402155223/sitebuilder/lib/core/controller/Controller.php:65
Stack trace:
#0 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150402155223/sitebuilder/config/initializers/dispatcher.php(336): Controller::load('ApiController', true)
#1 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150402155223/sitebuilder/lib/lithium/util/collection/Filters.php(183): {closure}('lithium\action\...', Array, Object(lithium\util\collection\Filters))
#2 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150402155223/sitebuilder/lib/lithium/core/StaticObject.php(126): lithium\util\collection\Filters::run('lithium\action\...', Array, Array)
#3 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150402155223/sitebuilder/lib/lithium/action/Dispatcher.php(124): lithium\core\StaticObject::_filter('run', Array, Object(Closure))
#4 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150402155223/sitebuilder/config/bootstrap.php(38): lithium\action\Dispatcher::run(Object(lithium\action\Request))
#5 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150402155223/segments/meumobi/public/index.php(5): {closure}('meumobi')
* Connection #0 to host int-meumobi.com left intact
#6 {main}</pre>
```

**Comment by elbidone** [comment]
/latest/items not exists, should use /items/latest. 
And the 401 response is right because the visitor.should_renew_password == true, then access to items is forbidden before save a new password

**Comment by elbidone** [comment]
I suggest to change the 401 response code, when visitor is authenticated but should renew password, to 403 response code (i.e. the user is authenticated but not authorized to access the resource).
> a 401 Unauthorized response should be used for missing or bad authentication, and a 403 Forbidden response should be used afterwards, when the user is authenticated but isn’t authorized to perform the requested operation on the given resource.
