### ISSUE TITLE
response time of images /upload/items/... is too slow, ~18sec

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#506]

**Comment by elbidone** [comment]
Images not exist, but meumobi doesn't return a 404 as expected
For example: http://meumobi.com/uploads/items/80x60_6956080.png

**Comment by elbidone** [comment]
![http___https_header_check](https://user-images.githubusercontent.com/9011612/36971655-6fbb561a-2064-11e8-8941-2e1de8fdfbe7.png)

**Comment by elbidone** [comment]
raises an exception
```
[2[2018-03-16 18:35:28] sitebuilder.DEBUG: "exception 'MissingControllerException' with message 'Missing Controller' in /home/meumobi/PROJECTS/meumobi.com/releases/20180314143917/sitebuilder/lib/core/controller/Controller.php:65 Stack trace: #0 /home/meumobi/PROJECTS/meumobi.com/releases/20180314143917/sitebuilder/config/initializers/dispatcher.php(356): Controller::load('UploadsControll...', true) #1 /home/meumobi/PROJECTS/meumobi.com/releases/20180314143917/sitebuilder/lib/lithium/util/collection/Filters.php(183): {closure}('lithium\\action\\...', Array, Object(lithium\util\collection\Filters)) #2 /home/meumobi/PROJECTS/meumobi.com/releases/20180314143917/sitebuilder/lib/lithium/core/StaticObject.php(126): lithium\util\collection\Filters::run('lithium\\action\\...', Array, Array) #3 /home/meumobi/PROJECTS/meumobi.com/releases/20180314143917/sitebuilder/lib/lithium/action/Dispatcher.php(124): lithium\core\StaticObject::_filter('run', Array, Object(Closure)) #4 /home/meumobi/PROJECTS/meumobi.com/releases/20180314143917/sitebuilder/config/bootstrap.php(34): lithium\action\Dispatcher::run(Object(lithium\action\Request)) #5 /home/meumobi/PROJECTS/meumobi.com/releases/20180314143917/segments/meumobi/public/index.php(5): {closure}('meumobi') #6 {main}" {"component":"general"}
```

**Comment by danconte72** [comment]
Should modify .htaccess in order to not use php when get uploads/items as static
