### ISSUE TITLE
Unable to run update_feeds, it raises FATAL ERROR

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#69]
```sh
# php update_feeds.php low
Fatal error: Uncaught exception 'MongoCursorException' with message 'localhost:27017: E11000 duplicate key error index: rimobi.extensions.$_id_  dup key: { : ObjectId('535fe310701796ae425fe5e9') }' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php:389
Stack trace:
#0 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php(389): MongoCollection->insert(Array, Array)
#1 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/core/Object.php(240): lithium\data\source\MongoDb->lithium\data\source\{closure}(Object(lithium\data\source\MongoDb), Array, NULL)
#2 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php(399): lithium\core\Object->_filter('lithium\data\so...', Array, Object(Closure))
#3 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/Model.php in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php on line 389
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/int-meumobilesite.com/current/sitebuilder/script# 
```

**Comment by elbidone** [comment]
occurs on environment rimobi: rimobi.ipanemax.com login=root&password=#abc123
No error logs on log/sitebuilder.log but feeds are not updated
I've check Triunfo feeds from site_id=10

**Comment by elbidone** [comment]
Done somes tests, I've removed the extension raising the error. But each time I removed the extension on error the next raises error too.
see below the logs and mongo commands done

```sh
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/int-meumobilesite.com/current# tail -10000f log/php.log |grep "dup key: {"
[28-Apr-2015 23:18:03 UTC] PHP Fatal error:  Uncaught exception 'MongoCursorException' with message 'localhost:27017: E11000 duplicate key error index: rimobi.extensions.$_id_  dup key: { : ObjectId('5432a56e701796664385fe23') }' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php:389
[28-Apr-2015 23:19:03 UTC] PHP Fatal error:  Uncaught exception 'MongoCursorException' with message 'localhost:27017: E11000 duplicate key error index: rimobi.extensions.$_id_  dup key: { : ObjectId('5432a56e701796664385fe23') }' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php:389
[28-Apr-2015 23:20:03 UTC] PHP Fatal error:  Uncaught exception 'MongoCursorException' with message 'localhost:27017: E11000 duplicate key error index: rimobi.extensions.$_id_  dup key: { : ObjectId('5432a56e701796664385fe23') }' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php:389
[28-Apr-2015 23:21:03 UTC] PHP Fatal error:  Uncaught exception 'MongoCursorException' with message 'localhost:27017: E11000 duplicate key error index: rimobi.extensions.$_id_  dup key: { : ObjectId('5432a56e701796664385fe23') }' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php:389
[28-Apr-2015 23:22:02 UTC] PHP Fatal error:  Uncaught exception 'MongoCursorException' with message 'localhost:27017: E11000 duplicate key error index: rimobi.extensions.$_id_  dup key: { : ObjectId('5432a56e701796664385fe23') }' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php:389
[28-Apr-2015 23:23:10 UTC] PHP Fatal error:  Uncaught exception 'MongoCursorException' with message 'localhost:27017: E11000 duplicate key error index: rimobi.extensions.$_id_  dup key: { : ObjectId('53ee1e65701796c30fc1e6ca') }' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php:389
[28-Apr-2015 23:24:09 UTC] PHP Fatal error:  Uncaught exception 'MongoCursorException' with message 'localhost:27017: E11000 duplicate key error index: rimobi.extensions.$_id_  dup key: { : ObjectId('53ee1e65701796c30fc1e6ca') }' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php:389
[28-Apr-2015 23:25:19 UTC] PHP Fatal error:  Uncaught exception 'MongoCursorException' with message 'localhost:27017: E11000 duplicate key error index: rimobi.extensions.$_id_  dup key: { : ObjectId('544669327017964c4994d7d9') }' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/lithium/data/source/MongoDb.php:389
```

```mongo
> db.extensions.find({_id: ObjectId('535fe310701796ae425fe5e9')});
{ "_id" : ObjectId("535fe310701796ae425fe5e9"), "category_id" : 59, "created" : ISODate("2014-04-29T17:36:16.183Z"), "enabled" : 1, "extension" : "rss", "modified" : ISODate("2014-05-29T17:06:15.427Z"), "site_id" : 7, "url" : "http://www.ri.santander.com.br/xml.aspx?idCanal=f4WnwaHDTluMhp3oWzAVFw==&linguagem=en" }
> db.extensions.remove({_id: ObjectId('535fe310701796ae425fe5e9')});
> db.extensions.find({_id: ObjectId('5432a56e701796664385fe23')});
{ "_id" : ObjectId("5432a56e701796664385fe23"), "category_id" : 212, "created" : ISODate("2014-10-06T14:21:34.489Z"), "enabled" : 1, "extension" : "rss", "modified" : ISODate("2014-11-05T20:46:16.519Z"), "priority" : 1, "site_id" : 15, "url" : "http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=Wcd4QWcnf4RWIXLQm2cXkQ==&tp=0" }
> db.extensions.remove({_id: ObjectId('5432a56e701796664385fe23')});
> db.extensions.find({_id: ObjectId('53ee1e65701796c30fc1e6ca')});
{ "_id" : ObjectId("53ee1e65701796c30fc1e6ca"), "category_id" : 200, "created" : ISODate("2014-08-15T14:51:17.712Z"), "enabled" : 1, "extension" : "rss", "modified" : ISODate("2014-11-07T15:40:50.344Z"), "priority" : 1, "site_id" : 15, "url" : "http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=NcDSh23/YI0Lheongw5msw==&tp=0", "use_html_purifier" : 0 }
> db.extensions.remove({_id: ObjectId('53ee1e65701796c30fc1e6ca')});
>
```

**Comment by elbidone** [comment]
I've tested an importation feed on the 3 ens. The same feed importation works ok on INT and PROD but not on CSE. 
But if I run update_feeds it always raises an ERROR
```sh
root@ns325644[ARPOADOR]:/home/meumobi/PROJECTS/int-meumobi.com/current/sitebuilder/script# php update_feeds.php low

Fatal error: Uncaught exception 'MongoDuplicateKeyException' with message 'localhost:27017: E11000 duplicate key error index: int_partners.extensions.$_id_  dup key: { : ObjectId('542d6da2b5a508e0628b4567') }' in /home/meumobi/PROJECTS/int-meumobi.com/releases/20150423132838/sitebuilder/lib/lithium/data/source/MongoDb.php:389
```

And on the three envs the ERROR exists on logs.

**Comment by elbidone** [comment]
I've ran a repair with no success

```sh
***** SERVER RESTARTED *****


Tue Apr 28 21:37:21 [initandlisten] MongoDB starting : pid=18192 port=27017 dbpath=/var/lib/mongodb 64
-bit host=CSE-MOBI-CL
Tue Apr 28 21:37:21 [initandlisten] db version v2.0.6, pdfile version 4.5
Tue Apr 28 21:37:21 [initandlisten] git version: nogitversion
Tue Apr 28 21:37:21 [initandlisten] build info: Linux z6 3.8-trunk-amd64 #1 SMP Debian 3.8.3-1~experim
ental.1 x86_64 BOOST_LIB_VERSION=1_49
Tue Apr 28 21:37:21 [initandlisten] options: { bind_ip: "127.0.0.1", config: "/etc/mongodb.conf", dbpa
th: "/var/lib/mongodb", logappend: "true", logpath: "/var/log/mongodb/mongodb.log", repair: true, smal
lfiles: "true" }
Tue Apr 28 21:37:21 [initandlisten] journal dir=/var/lib/mongodb/journal
Tue Apr 28 21:37:21 [initandlisten] recover : no journal files present, no recovery needed
Tue Apr 28 21:37:21 [initandlisten] ****
Tue Apr 28 21:37:21 [initandlisten] ****
Tue Apr 28 21:37:21 [initandlisten] need to upgrade database rimobi with pdfile version 4.5, new versi
on: 4.5
Tue Apr 28 21:37:21 [initandlisten]      starting upgrade
Tue Apr 28 21:37:21 [initandlisten]  rimobi repairDatabase rimobi
Tue Apr 28 21:37:21 [initandlisten] removeJournalFiles
Tue Apr 28 21:37:21 [FileAllocator] allocating new datafile /var/lib/mongodb/$tmp_repairDatabase_0/rim
obi.ns, filling with zeroes...
Tue Apr 28 21:37:21 [FileAllocator] creating directory /var/lib/mongodb/$tmp_repairDatabase_0/_tmp
Tue Apr 28 21:37:21 [FileAllocator] done allocating datafile /var/lib/mongodb/$tmp_repairDatabase_0/ri
mobi.ns, size: 16MB,  took 0.002 secs
Tue Apr 28 21:37:21 [FileAllocator] allocating new datafile /var/lib/mongodb/$tmp_repairDatabase_0/rim
obi.0, filling with zeroes...
Tue Apr 28 21:37:21 [FileAllocator] done allocating datafile /var/lib/mongodb/$tmp_repairDatabase_0/ri
mobi.0, size: 16MB,  took 0.002 secs
Tue Apr 28 21:37:21 [initandlisten] build index rimobi.remenber { _id: 1 }
Tue Apr 28 21:37:21 [FileAllocator] allocating new datafile /var/lib/mongodb/$tmp_repairDatabase_0/rim
obi.1, filling with zeroes...
Tue Apr 28 21:37:21 [FileAllocator] done allocating datafile /var/lib/mongodb/$tmp_repairDatabase_0/ri
mobi.1, size: 32MB,  took 0.002 secs
Tue Apr 28 21:37:21 [initandlisten] build index done 127 records 0.003 secs
Tue Apr 28 21:37:21 [initandlisten] build index rimobi.extensions { _id: 1 }
Tue Apr 28 21:37:21 [initandlisten] build index done 203 records 0.001 secs
Tue Apr 28 21:37:21 [initandlisten] build index rimobi.skins { _id: 1 }
Tue Apr 28 21:37:21 [initandlisten] build index done 45 records 0 secs
Tue Apr 28 21:37:21 [initandlisten] build index rimobi.items { _id: 1 }
Tue Apr 28 21:37:21 [initandlisten] build index done 5310 records 0.024 secs
Tue Apr 28 21:37:21 [initandlisten] build index rimobi.invites { _id: 1 }
Tue Apr 28 21:37:21 [initandlisten] build index done 4 records 0 secs
Tue Apr 28 21:37:21 [initandlisten] build index rimobi.visitors { _id: 1 }
Tue Apr 28 21:37:21 [initandlisten] build index done 3 records 0.001 secs
Tue Apr 28 21:37:22 [initandlisten] removeJournalFiles
Tue Apr 28 21:37:22 [initandlisten] finished checking dbs
Tue Apr 28 21:37:22 dbexit: 
Tue Apr 28 21:37:22 [initandlisten] shutdown: going to close listening sockets...
Tue Apr 28 21:37:22 [initandlisten] shutdown: going to flush diaglog...
Tue Apr 28 21:37:22 [initandlisten] shutdown: going to close sockets...
Tue Apr 28 21:37:22 [initandlisten] shutdown: waiting for fs preallocator...
Tue Apr 28 21:37:22 [initandlisten] shutdown: lock for final commit...
Tue Apr 28 21:37:22 [initandlisten] shutdown: final commit...
Tue Apr 28 21:37:22 [initandlisten] shutdown: closing all files...
Tue Apr 28 21:37:22 [initandlisten] closeAllFiles() finished
Tue Apr 28 21:37:22 [initandlisten] journalCleanup...
Tue Apr 28 21:37:22 [initandlisten] removeJournalFiles
Tue Apr 28 21:37:22 [initandlisten] shutdown: removing fs lock...
Tue Apr 28 21:37:22 dbexit: really exiting now
```

**Comment by elbidone** [comment]
All post about this bug comment an error of duplicate index.
The only code responsible to create extension is the extension_controller and suprisingly the UpdateFeedService.
I've replaced on UpdateFeedService $extension = Rss::create($data); by Extensions::find. And it seems to work, I didn't observe anymore this ERROR msg on logs.

I didn't commit anything

```php
//$extension = Rss::create($data);
      $extension = Extensions::find('type', array('conditions' => array(
      '_id' => $data['_id'],
      'site_id' => $data['site_id'],
    )));
```

To resume:

- It's an old bug (as long as php log gone)
- we can observed it on all ENVs.
- easy to reproduce, set only one extension with priority $gte 1. It will raise it
- I can't understand why on PROD it raises each minute this ERROR with no extension to run: db.extensions.find({priority: {$gte: 0}}).count() == 0, on CSE it ONLY raises this ERROR IF AND ONLY IF db.extensions.find({priority: {$gte: 0}}).count() > 0 

Conclusion: we knew it but now it's sure, a refactor of RSS management is required!

**Comment by elbidone** [comment]
maybe my find should use .limit(1)

**Comment by t4deu** [comment]
There is no need to "limit", because you are filtering by "id"

**Comment by t4deu** [comment]
And yes, is a old bug, a ticket was created on goplan, now is the issue #8.

**Comment by juliogreff** [comment]
@elbidone your fix looks fine, I have no clue why we try to create an extension there, doesn't make much sense to me. You can commit it and close the issue.
