### ISSUE TITLE
Multiple MongoDuplicateKeyException errors in the log

### ISSUE THREAD

**Issue by juliogreff** [meumobi/sitebuilder#8]
This is happening on INT server

$ tail log/php-2015-03-13.log
[13-Mar-2015 06:45:03 UTC] PHP Fatal error:  Uncaught exception 'MongoDuplicateKeyException' with message 'localhost:27017: E11000 duplicate key error index: int_partners.extensions.$_id_  dup key: { : ObjectId('542d6da2b5a508e0628b4567') }' in /home/meumobi/PROJECTS/int-meumobi.com/releases/20150312174458/sitebuilder/lib/lithium/data/source/MongoDb.php:389
Stack trace:
#0 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150312174458/sitebuilder/lib/lithium/data/source/MongoDb.php(389): MongoCollection->insert(Array, Array)
#1 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150312174458/sitebuilder/lib/lithium/core/Object.php(240): lithium\data\source\MongoDb->lithium\data\source\{closure}(Object(lithium\data\source\MongoDb), Array, NULL)
#2 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150312174458/sitebuilder/lib/lithium/data/source/MongoDb.php(399): lithium\core\Object->_filter('lithium\data\so...', Array, Object(Closure))
#3 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150312174458/sitebuilder/lib/lithium/data/Model.php(773): lithium\dat in /home/meumobi/PROJECTS/int-meumobi.com/releases/20150312174458/sitebuilder/lib/lithium/data/source/MongoDb.php on line 389

**Comment by juliogreff** [comment]
#69 has more details. I'm closing this one as a duplicate.
