### ISSUE TITLE
sitebuilder.ERROR: error executing worker raised on INT

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#86]
Full of following messages on INT, please check also on PROD
```
[2015-05-21 15:05:02] sitebuilder.INFO: start executing worker {"worker":"meumobi\\sitebuilder\\workers\\PushNotificationWorker","job id":"555dd77bb5a508c50e8b4574","job type":"push_notification"} 
[2015-05-21 15:05:02] sitebuilder.ERROR: error executing worker {"worker":"meumobi\\sitebuilder\\workers\\PushNotificationWorker","job_id":"555dd77bb5a508c50e8b4574","job type":"push_notification","exception":"app\\models\\RecordNotFoundException","message":"item not found","trace":"#0 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/app/models/Items.php(682): app\\models\\Items::typeFinder('app\\models\\Item...', Array, Object(lithium\\util\\collection\\Filters))\n#1 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/lib/lithium/util/collection/Filters.php(183): lithium\\core\\Libraries::app\\models\\{closure}('app\\models\\Item...', Array, Object(lithium\\util\\collection\\Filters))\n#2 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/lib/lithium/core/StaticObject.php(126): lithium\\util\\collection\\Filters::run('app\\models\\Item...', Array, Array)\n#3 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/lib/lithium/data/Model.php(993): lithium\\core\\StaticObject::_filter('find', Array, Object(Closure), Array)\n#4 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/lib/lithium/data/Model.php(457): lithium\\data\\Model::_filter('find', Array, Object(Closure), Array)\n#5 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/lib/meumobi/sitebuilder/workers/Worker.php(54): lithium\\data\\Model::find('type', Array)\n#6 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/lib/meumobi/sitebuilder/workers/Worker.php(64): meumobi\\sitebuilder\\workers\\Worker->getItem()\n#7 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/lib/meumobi/sitebuilder/workers/PushNotificationWorker.php(17): meumobi\\sitebuilder\\workers\\Worker->getSite()\n#8 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/lib/meumobi/sitebuilder/WorkerManager.php(43): meumobi\\sitebuilder\\workers\\PushNotificationWorker->perform()\n#9 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/script/perform_works.php(8): meumobi\\sitebuilder\\WorkerManager::execute(Object(meumobi\\sitebuilder\\workers\\PushNotificationWorker))\n#10 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/config/cli.php(19): {closure}()\n#11 /home/meumobi/PROJECTS/int-meumobi.com/releases/20150521125325/sitebuilder/script/perform_works.php(10): meumobi_lock('perform_works', Object(Closure))\n#12 {main}"} 
```

**Comment by t4deu** [comment]
this happens when the item of a push notification job not exists anymore, probably because the item has removed before the job execute. the job is also removed after the error.

To prevent this, need to remove any scheduled job for an item before the item be removed using an observer

**Comment by juliogreff** [comment]
I'd rather just catch the exception and do nothing instead of adding more logic in observers that are already very prone to bugs.

**Comment by t4deu** [comment]
The exception already has a catch, the error log is from there, so I'm gonna improve the log a little bit adding the job params

**Comment by elbidone** [comment]
If the job is also removed after the error, why the error occurs 81049 times, see grep below ? It continues 20-30 times per hour today and nobody editing anything on INT.

```sh
root@ns325644[ARPOADOR]:/home/meumobi/PROJECTS/int-meumobi.com/current# grep "error executing worker" log/sitebuilder.log | wc -l
81049
```

**Comment by t4deu** [comment]
Because before the @juliogreff update on the feeds import a lot of items are created and removed on each import, this still happens, but the amount is less. If you go check on the database there is no job registered
