### ISSUE TITLE
update_feeds doesn't work on PROD because a site is missing...

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#91]
# php update_feeds.php high

Fatal error: Uncaught exception 'app\models\RecordNotFoundException' with message 'Sites with id=69 not found' in /home/meumobi/PROJECTS/meumobi.com/releases/20150508192157/sitebuilder/app/models/app_model.php:28
Stack trace:
#0 /home/meumobi/PROJECTS/meumobi.com/releases/20150508192157/sitebuilder/app/models/categories.php(296): AppModel->firstById('69')
#1 [internal function]: Categories->updateParentTimestamps(false)
#2 /home/meumobi/PROJECTS/meumobi.com/releases/20150508192157/sitebuilder/lib/core/common/Hookable.php(52): call_user_func_array(Array, Array)
#3 /home/meumobi/PROJECTS/meumobi.com/releases/20150508192157/sitebuilder/lib/core/common/Hookable.php(16): Hookable->callHook('updateParentTim...', Array)
#4 /home/meumobi/PROJECTS/meumobi.com/releases/20150508192157/sitebuilder/lib/core/model/Model.php(395): Hookable->fireAction('afterSave', Array)
#5 /home/meumobi/PROJECTS/meumobi.com/releases/20150508192157/sitebuilder/app/models/extensions/Rss.php(91): Model->save()
#6 [internal function]: app\models\extensions in /home/meumobi/PROJECTS/meumobi.com/releases/20150508192157/sitebuilder/app/models/app_model.php on line 28
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/releases/20150508192157/sitebuilder/script#

**Comment by elbidone** [comment]
the extension 7113 of site 445 is enabled but importation not run

**Comment by t4deu** [comment]
On the feed importation the error was not wrapped by the try catch block, so the import stops, check if the refactoring was already fixed this

**Comment by t4deu** [comment]
Also check if the priority values are consistent across the import job

**Comment by t4deu** [comment]
The refactoring already handle when the site is missing, here the log of this error:
```
[2015-05-22 10:56:12] sitebuilder.INFO: updating feeds {"priority":0} 
[2015-05-22 10:57:09] sitebuilder.DEBUG: updated feeds {"55478d66297e6b05368b4567":{"extension_id":"55478d66297e6b05368b4567","total_articles":30,"updated_articles":24,"created_articles":6,"removed_articles":0,"total_images":0,"failed_images":0,"category_id":"3"},"5552121a297e6b8d268b4567":{"extension_id":"5552121a297e6b8d268b4567","total_articles":25,"updated_articles":25,"created_articles":0,"removed_articles":0,"total_images":25,"failed_images":0,"category_id":"5"},"5552171b297e6b9c048b4567":{"extension_id":"5552171b297e6b9c048b4567","total_articles":10,"updated_articles":9,"created_articles":1,"removed_articles":0,"total_images":0,"failed_images":0,"category_id":"6"},"555f2e79297e6b89058b4567":{"extension_id":"555f2e79297e6b89058b4567","total_articles":10,"updated_articles":9,"created_articles":1,"removed_articles":0,"total_images":0,"failed_images":0,"category_id":"11"}} 
[2015-05-22 10:57:09] sitebuilder.INFO: finished updating feeds {"total_updated_feeds":4,"total_failed_feeds":1,"failed_feeds":[{"extension_id":"555f350d297e6b88058b4567","error":"Sites with id=3 not found"}],"priority":0,"elapsed_time":56.408473968506}
```

**Comment by t4deu** [comment]
And the priority values only are defined only in the Worker  class in `lib/meumobi/sitebuilder/workers/Worker.php`
